config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'houses#index'
  
  resources :houses, only: [:index]
  resources :abouts, only: [:index]
  resources :posts, only: [:index, :create]
  resources :inquiries, only: [:new, :create]
  resources :constructions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/construction.rb
class Construction < ApplicationRecord
  belongs_to :user
  has_one_attached :image
end

app/models/house.rb
class House < ApplicationRecord
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord

  # attr_accessor :name, :email, :message

  # validates :name, presence: true
  # validates :email, presence: true
  # validates :message, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :constructions
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/constructions_controller.rb
class ConstructionsController < ApplicationController
  before_action :set_construction, only: [:show, :edit, :update]

  def index
    @constructions = Construction.includes(:user).order("created_at DESC")
  end

  def new
    @construction = Construction.new
  end

  def create
    @construction = Construction.new(construction_params)
    if @construction.save
      redirect_to constructions_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @construction.update(construction_params)
      redirect_to construction_path(@construction.id)
    else
      render :edit
    end
  end

  def destroy
    construction = Construction.find(params[:id])
    if construction.destroy
      redirect_to root_path 
    end
  end



  private
  def construction_params 
    params.require(:construction).permit(:image, :name, :message).merge(user_id: current_user.id)
  end

  def set_construction
    @construction = Construction.find(params[:id])
  end

end

app/controllers/houses_controller.rb
class HousesController < ApplicationController

  def index
  end

end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  def new
    @inquiry = Inquiry.new
  end

  def create
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.save 
      InquiryMailer.send_mail(@inquiry)
      redirect_to root_path
    else
      render :new
    end
  end


  private
    def inquiry_params
      params.require(:inquiry).permit(:name, :email, :message)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order(id: "DESC")
  end
  
  def create
    post = Post.create(content: params[:content])
    render json:{ post: post }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/constructions_helper.rb
module ConstructionsHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/informations_helper.rb
module InformationsHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/abouts/index.html.erb
<%= render "shared/header"%> 
<div class="wrapper">
  <h1>Corporate Guide..</h1>
  <ul class="wrapper-left">
    <li>会社内容</li>
    <li>所在地</li>
    <li>TEL</li>
    <li> FAX</li>
    <li> E-mail</li>
    <li> 代表者</li>
    <li>事業内容</li>
    <li>許可登録</li>
  </ul>
  <ul class="wrapper-right">
    <li>有限会社篠原工務店</li>
    <li>長野県諏訪市中洲福島5455-48</li>
    <li>0266-57-5788</li>
    <li>0266-58-6667</li>
    <a href="#"><li>info@k-shinohara.com<li></a>
    <li>篠原威治 [Shinohara Takeharu</li>
    <li>設計・施工・監理</li>
    <li>長野県知事許可（般2）第19370号</li>
  </ul>
  <div class="maps">
    <div class="map">
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3226.8476740839633!2d138.11333231526822!3d36.02401298011579!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x601c55d42cfaa25f%3A0x5cb4b87a24419eb9!2z77yI5pyJ77yJ56-g5Y6f5bel5YuZ5bqX!5e0!3m2!1sja!2sjp!4v1600611325076!5m2!1sja!2sjp" width="400" height="300" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
    </div>
  </div>
  <div class="links">
    <h2>Links..</h2>
    <ul class="link">
      <a href="http://www.chuden.co.jp/" target="_blank"><li>中部電化（オール電化のご案内）</li></a>
      <a href="http://www.tostem.co.jp/" target="_blank"><li>トステム（新築＆リフォーム。サッシからキッチン）</li></a>
      <a href="http://www.yatsu-akadake.com/" target="_blank"><li>八ヶ岳本沢温泉グループ（当社が施工をした山小屋もあり）</li></a>
      <a href="http://www.takachiho-corp.co.jp/materials_2.html" target="_blank"><li>薩摩中霧島壁（100％自然素材の内装用仕上げ材）</li></a>
    </ul>
  </div>
</div>
<%= render "shared/footer"%>

app/views/constructions/edit.html.erb
<%= render "shared/header"%> 
<div class="wrapper-d">
  <div class="wapper-e"> 
    <h1>投稿編集画面</h1>
    <%= form_with model: @construction,  local: true do |f| %>  
    <%#= render 'shared/error_messages', model: f.object %>
    <%# 投稿画像 %>
    <div class="image-upload">
      <div class="weight-bold-text">
        投稿画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /投稿画像 %>
    <%# 施工例名とメッセージ %>
    <div class="new-items">
      <%= f.text_field :name, class:"items-name", id:"item-name", placeholder:"施工名", maxlength:"30" %>
      <%= f.text_area :message, class:"items-text", id:"item-info", placeholder:"住宅の説明(篠原工務店 自宅＆ショールームなど...)" ,rows:"7" ,maxlength:"1000" %>
    </div>
    <%# /施工名とメッセージ %>
    <%# 下部ボタン %>
    <div class="push-btn-contents">
      <%= f.submit "投稿する" ,class:"push-btn" %>
    </div>
    <%# /下部ボタン %>
  <% end %>
  </div>
</div>

app/views/constructions/index.html.erb
<%= render "shared/header"%> 
<div class="wrapper-a">
  <div class="wapper-b"> 
    <h1>施工例</h1>

    <%# /施工例画像と名前%>
    <div class="item-contents">
      <ul class="item-lists">
        <% @constructions.each do |construction|%>
        <li class="list">
          <%= link_to construction_path(construction.id),  method: :get, class: "item-name"  do %>
          <div class="item-img-content">
            <%= image_tag construction.image , class: "item-img" if construction.image.attached? %>
          </div>
          <div class="item-info">
            <h3 class="item-name">
              <%= construction.name %>
            </h3>
          </div>
          <% end %>
        </li>
        <% end %>
      </ul>
    <div> 
  
    <%# //施工例一覧 %>
  </div>
</div>
<%# 投稿ボタン%>
<div class="purchase-btn">
  <% if user_signed_in? %>
    <a href="/constructions/new">
    <%= image_tag 'wraite.png' , size: '50x30' ,class: "purchase-btn-icon" %>
    </a> 
  <% end %>
 </div>  
<%# 投稿ボタン%>
<%= render "shared/footer"%>

app/views/constructions/new.html.erb
<%= render "shared/header"%> 
<div class="wrapper-b">
  <div class="wapper-c"> 
  <h1>投稿画面</h1>
  <%= form_with model: @construction,  local: true do |f| %>  
    <%#= render 'shared/error_messages', model: f.object %>
    <%# 投稿画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        ※投稿画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /投稿画像 %>
    <%# 施工例名とメッセージ %>
    <div class="new-items">
      <%= f.text_field :name, class:"items-name", id:"item-name", placeholder:"施工名", maxlength:"30" %>
      <%= f.text_area :message, class:"items-text", id:"item-info", placeholder:"住宅の説明(篠原工務店 自宅＆ショールームなど...)" ,rows:"7" ,maxlength:"1000" %>
    </div>
    <%# /施工名とメッセージ %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "投稿する" ,class:"sell-btn" %>
    </div>
    <%# /下部ボタン %>
  <% end %>
  </div>
</div>

app/views/constructions/show.html.erb
<%= render "shared/header"%> 
<div class="wrapper-c">
  <div class="wapper-d"> 
    <div class="item-box">
      <div class="box">
        <h1 class="name">
          <%= @construction.name %>
        </h1>
        <h2 class="message">
          <%= @construction.message %>
        </h2>
      </div>
      <button onclick="history.back()" class="button">前のページへ戻る</button>
      <%#= image_tag @construction.image, class:"item-box-img" %>
      <div class="bar">
        <%= image_tag @construction.image, class:"item-box-img" %>
        <% if user_signed_in? && current_user.id == @construction.user_id %>
          <%= link_to '編集', edit_construction_path(@construction.id), method: :get, class: "item-red-btn" %>
          <p class='or-text'>or</p>
          <%= link_to '削除', construction_path(@construction.id), method: :delete, class:'item-destroy' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/houses/index.html.erb
<%= render "shared/header" %>
<div class="main">
  <div id="top-wrapper"> 
    <div class="top-container">
      <h1>健康に暮らせる家・永く愛着がもてる家</h1>
      <h2>プロの大工から見た監理・設計・施工でお客様の夢をカタチに。</h2>
    </div>
  </div>
  <!-- main背景 -->
  <div class="top-wrapper">
  </div>
  <!-- main first -->
  <div class="main-wrapper">
    <div class="main-contents">
      <div class="f-contents">
        <ul>
          <li><div>毎日くらす場所だから、<br>いつも、すこやかに、ここちよく過ごしたい。<br>家族の健康を考えて自然素材をできるだけ...</div></li>
          <li class="img01"><%= image_tag"image03.jpg", width:"", height:"", class:"img01" %> </li>
          <li class="img02"><%= image_tag"image04.jpg", width:"", height:"", class:"img02" %></li>
        </ul>
      </div>
      <!-- main second -->
      <div class="s-contents">
        <div>外断熱パネル工法、アルミ箔が 熱を跳ね返し家全体を保温。<br>床暖房も空気の熱を使ったヒートポンプ式を採用。<br>ダイニングにはテラコッタ調のタイル張りホール、廊下にも真っ白なタイル床暖房ですから夏は涼しく、冬暖かい。</div>
        <ul>
          <li class="img03"><%= image_tag"image05.jpg", width:"", height:"", class:"img03" %></li>
          <li class="img04"><%= image_tag"image06.jpg", width:"", height:"", class:"img04" %></li>
          <li class="img05"><%= image_tag"image07.jpg", width:"", height:"", class:"img05" %></li>
        </ul>
      </div>
      <!-- main third -->　
      <div class="t-wrapper">
        <div class="t-contents">
          <div class="t-content">
            <div>Works.</div>
            <ul>
              <li><%= image_tag"image08.jpg", width:"", height:"", class:"img06"%></li>
              <li><%= image_tag"image09.jpg", width:"", height:"", class:"img07"%></li>
              <li><%= image_tag"image10.jpg", width:"", height:"", class:"img08"%></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <!-- footer -->
    <div class="footer-wrapper">
      <div class="footer-contents">
        <div class="footer-left">
          <div class="footer-tittle"><p>篠原工務店</p></div>
          <div><p>〒392-0015</p>
               <p>長野県諏訪市中洲5455-45</p> 
               <p>TEL: 0266-57-5788</p>
          </div>
        </div>
        <div class="footer-right">
          <ul>
            <li><%= link_to '最新情報', posts_path, class: "news"%></li>
            <li><%= link_to '施工例', constructions_path, class: "construction"%></li>
            <li><%= link_to '会社案内', abouts_path, class: "information"%></li>
            <li><%#= link_to 'お問い合わせ', new_inquiry_path, class: "contact"%></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/informations/show.html.erb
<%= render "shared/header"%> 
<div class="wrapper">
  <%= image_tag "image07.png", class:"show-pict1" %>
  <h1>Corporate Guide..</h1>
  <ul class="wrapper-left">
    <li>会社内容</li>
    <li>所在地</li>
    <li>TEL</li>
    <li> FAX</li>
    <li> E-mail</li>
    <li> 代表者</li>
    <li>事業内容</li>
    <li>許可登録</li>
  </ul>
  <ul class="wrapper-right">
    <li>有限会社篠原工務店</li>
    <li>長野県諏訪市中洲福島5455-48</li>
    <li>0266-57-5788</li>
    <li>0266-58-6667</li>
    <a href="#"><li>info@k-shinohara.com<li></a>
    <li>篠原威治 [Shinohara Takeharu</li>
    <li>設計・施工・監理</li>
    <li>長野県知事許可（般12）第019370号</li>
  </ul>
  <div class="maps">
    <div class="map">
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3226.8476740839633!2d138.11333231526822!3d36.02401298011579!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x601c55d42cfaa25f%3A0x5cb4b87a24419eb9!2z77yI5pyJ77yJ56-g5Y6f5bel5YuZ5bqX!5e0!3m2!1sja!2sjp!4v1600611325076!5m2!1sja!2sjp" width="400" height="300" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
    </div>
  </div>
  <div class="links">
    <h2>Links..</h2>
    <ul class="link">
      <a href="http://www.chuden.co.jp/"><li>中部電化（オール電化のご案内）</li></a>
      <a href="http://www.tostem.co.jp/"><li>トステム（新築＆リフォーム。サッシからキッチン）</li></a>
      <a href="http://www.yatsu-akadake.com/"><li>八ヶ岳本沢温泉グループ（当社が施工をした山小屋もあり）</li></a>
      <a href="http://www.takachiho-corp.co.jp/materials_2.html"><li>薩摩中霧島壁（100％自然素材の内装用仕上げ材）</li></a>
    </ul>
  </div>
</div>
<%= render "shared/footer"%>

app/views/inquiries/new.html.erb
<%= render "shared/header"%> 
<div class="i-wrapper">
  <div class="i-wapper"> 
    <h1>Contact Form..</h1>
    <%= form_with model: @inquiry, local: true do |f| %>
      <%= f.text_field :name, placeholder: "NAME", class: "small-field" %>
      <%= f.text_field :email, placeholder: "e-mail", class: "small-field" %>
      <%= f.text_area :message, placeholder: "MESSAGE", class: "large-field" %>
      <%= f.submit "SEND", class: "send" %>
    <% end %>
  </div>
</div>
<%= render "shared/footer" %>  

app/views/layouts/application.html.erb
  <!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
	<title>篠原工務店</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all'%>
  <%= javascript_pack_tag 'application' %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>

<body>
  <%= yield %>
</body>

</html>

app/views/posts/index.html.erb
<%= render "shared/header"%> 
<div class="p-wrapper">
  <div class="p-wapper"> 
    <%= form_with url: "/posts", method: :post ,id: "form" do |form| %>
      <% if user_signed_in? && current_user.id %>
        <%= form.text_field :content, id: "content" %>
        <%= form.submit '投稿する' , id: "submit" %>
      <% end %>
    <% end %>
    <div id="list"></div>
    <% @posts.each do |post| %>
    <div class="post" >
      <div class="post-date">
        投稿日時：<%= l post.created_at %>
      </div>
      <div class="post-content">
        <%= post.content %>
      </div>
    </div>
    <% end %>
  </div> 
</div>
<%= render "shared/footer"%>

app/views/shared/_footer.html.erb
<div class="s-footer-wrapper">
      <div class="s-footer-contents">
        <div class="s-footer-left">
          <div class="s-footer-tittle"><p>篠原工務店</p></div>
          <div><p>〒392-0015</p>
               <p>長野県諏訪市中洲5455-45</p> 
               <p>TEL: 0266-57-5788</p>
          </div>
        </div>
        <div class="s-footer-right">
          <ul>
            <li><%= link_to '最新情報', posts_path, class: "s-footer-news"%></li>
            <li><%= link_to '施工例', constructions_path, class: "s-footer-construction"%></li>
            <li><%= link_to '会社案内', abouts_path, class: "s-footer-information"%></li>
            <li><%= link_to 'お問い合わせ', new_inquiry_path, class: "s-footer-contact"%></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_header.html.erb
<header>
  <div class="header-left">
    <a href="/"><i class="far far fa-smile fa-3x"></i></a>
  </div>
  <div class="nav-bar">
    <ul>
      <li><%= link_to '最新情報',posts_path, class: "header-news"%></li>
      <li><%= link_to '施工例', constructions_path,  class: "header-construction"%></li>
      <li><%= link_to '会社案内', abouts_path, class: "header-information"%></li>
      <li><%#= link_to 'お問い合わせ', new_inquiry_path, class: "header-contact"%></li>
    </ul>
  </div>
  <div class="nav">
   <ul class='lists-right'>
    <% if user_signed_in? %>
      <li><%= link_to destroy_user_session_path, method: :delete, class: "fas" do %>
        <i class="fas fa-lock"></i>
      <% end %> 
    <% else %>
      <a href="/users/sign_in"><i class="fas fa-lock-open fa-1x"></i></a>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
    <% end %>
    </ul>
  </div>
</header>